// <auto-generated />
using System;
using System.Collections.Generic;
using Gittez.Core.Models;
using Gittez.Infrastructure.Persistence;
using Gittez.Infrastructure.Persistence.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gittez.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GittezDbContext))]
    [Migration("20260728124356_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gittez.Infrastructure.Persistence.Entities.IssueCacheEntry", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int>("BodyLength")
                        .HasColumnType("integer")
                        .HasColumnName("body_length");

                    b.Property<int>("CommentCount")
                        .HasColumnType("integer")
                        .HasColumnName("comment_count");

                    b.Property<short>("Difficulty")
                        .HasColumnType("smallint")
                        .HasColumnName("difficulty");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<bool>("HasAssignee")
                        .HasColumnType("boolean")
                        .HasColumnName("has_assignee");

                    b.Property<string>("HtmlUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("html_url");

                    b.Property<DateTimeOffset>("IssueCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issue_created_at");

                    b.Property<DateTimeOffset>("IssueUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issue_updated_at");

                    b.PrimitiveCollection<string>("Labels")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("labels");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<string>("RepoFullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("repo_full_name");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("RepoFullName")
                        .HasDatabaseName("ix_issue_cache_repo");

                    b.ToTable("issue_cache", (string)null);
                });

            modelBuilder.Entity("Gittez.Infrastructure.Persistence.Entities.ProfileEntity", b =>
                {
                    b.Property<string>("GithubLogin")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("github_login");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.PrimitiveCollection<string>("Interests")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("interests");

                    b.Property<int>("MedianSizeKb")
                        .HasColumnType("integer")
                        .HasColumnName("median_size_kb");

                    b.Property<int>("PublicRepoCount")
                        .HasColumnType("integer")
                        .HasColumnName("public_repo_count");

                    b.Property<List<ProfileLanguage>>("TopLanguages")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("top_languages");

                    b.HasKey("GithubLogin");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("Gittez.Infrastructure.Persistence.Entities.RepoCacheEntry", b =>
                {
                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<RepoCandidate>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<string>("ETag")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("etag");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<List<ScoreComponent>>("HealthBreakdown")
                        .HasColumnType("jsonb")
                        .HasColumnName("health_breakdown");

                    b.Property<DateTimeOffset?>("HealthComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("health_computed_at");

                    b.Property<decimal?>("HealthScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("health_score");

                    b.HasKey("FullName");

                    b.HasIndex("FetchedAt")
                        .HasDatabaseName("ix_repo_cache_fetched");

                    b.ToTable("repo_cache", (string)null);
                });

            modelBuilder.Entity("Gittez.Infrastructure.Persistence.Entities.SessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.HasKey("Id");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("Gittez.Infrastructure.Persistence.Entities.WatchlistItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("RepoFullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("repo_full_name");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_watchlist_session");

                    b.HasIndex("SessionId", "RepoFullName")
                        .IsUnique();

                    b.ToTable("watchlist_items", (string)null);
                });

            modelBuilder.Entity("Gittez.Infrastructure.Persistence.Entities.WatchlistItem", b =>
                {
                    b.HasOne("Gittez.Infrastructure.Persistence.Entities.SessionEntity", "Session")
                        .WithMany("Items")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Gittez.Infrastructure.Persistence.Entities.SessionEntity", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
